"""empty message

Revision ID: 904cacff99da
Revises: beedf46f9909
Create Date: 2019-03-18 02:40:46.611857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904cacff99da'
down_revision = 'beedf46f9909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('date', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'date')
    # ### end Alembic commands ###
